In [1]:
# from numba import cuda
import paicos as pa
import numpy as np
import cupy as cp
import turbocluster as tc
import math
from numba import cuda
import nvtx
import finufft

import cmasher as cmr
%matplotlib widget
import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm, Normalize

pa.settings.strict_units = False



In [21]:
# A snapshot object
# snap = pa.Snapshot(pa.data_dir, 247)
# snap = pa.Snapshot('/lustre/astro/berlok/zoom-simulations-new-ics/halo_0003/adiabatic-mhd/zoom4_ics_v1/output', 247)
snap = pa.Snapshot('/lustre/astro/berlok/zoom-simulations-new-ics/halo_0003/tng/zoom12_ics_v1/output', 247)
# snap = pa.Snapshot('/scratch/lperrone/zoom-simulations-new-ics/halo_0003/tng/zoom12_ics_v1/output', 247)
# snap = pa.Snapshot('/llust21/cosmo-plasm/zoom-simulations-arepo2/halo_0003/tng/zoom12/output', 
#                    305, basename='snapshot')
center = snap.Cat.Group['GroupPos'][0]
widths = np.array([2e2, 1e2, 3.8e2], dtype=float)


Gauss = snap.uq('G')
arepo_length = snap.length
density_unit = snap['0_Density'].uq
L_box = (arepo_length*(widths[0]))

In [22]:
pe = tc.PotentialEnergy(snap, center, widths, snap['0_Coordinates'], snap['0_Masses'], npix=256)

In [15]:
np.sum(pe.tile.mass_per_tile)

array(346.46607631)

In [16]:
np.sum(snap['0_Masses'][pe.index])

<PaicosQuantity 339.7338597 arepo_mass / small_h>

In [17]:
np.sum(pe.index)

404093

In [18]:
np.sum(pe.tile.particles_per_tile)

array(404093)

In [8]:
smoothing_length = 10*arepo_length

In [9]:
smoothing_length

<PaicosQuantity 10 arepo_length small_a / small_h>

In [10]:
pe.compute_potential(smoothing_length)

<PaicosQuantity 0. arepo_mass2 / (arepo_length small_a small_h)>

In [11]:
pe.tile.off_sets

array([499698.09375, 499779.25   , 499610.65625])

In [23]:
pe.tile.tile_widths

array([0.78125 , 0.78125 , 0.781893])

In [24]:
pe.tile.npixs

array([256, 128, 486])